force-app/main/default/objects/Contact_Badge_Definition__mdt/Contact_Badge_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Used to define criteria for and appearance of Contact Badges</description>
    <label>Contact Badge Definition</label>
    <pluralLabel>Contact Badge Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Additional_Detail_Fields__c.field-meta.xml
<CustomField>
    <fullName>Additional_Detail_Fields__c</fullName>
    <description>Enter API field names, separated by commas, for any fields that should be displayed when a user selects a badge</description>
    <inlineHelpText>Enter API field names, separated by commas, for any fields that should be displayed when a user selects a badge</inlineHelpText>
    <label>Additional Detail Fields</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Label_Field_Reference__c.field-meta.xml
<CustomField>
    <fullName>Label_Field_Reference__c</fullName>
    <description>If Badge Label Type is set to &apos;Field Reference&apos;, enter the API Name of the field on the target object to reference for the badge label.</description>
    <inlineHelpText>If Badge Label Type is set to &apos;Field Reference&apos;, enter the API Name of the field on the target object to reference for the badge label.</inlineHelpText>
    <label>Label Field Reference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactBadgesHelper.cls
public without sharing class ContactBadgesHelper {

    public static String getQueryFromDefinition(Contact_Badge_Definition__mdt definition) {
        
        String query = 'SELECT Id ';

        if (!String.isBlank(definition.Label_Field_Reference__c)) {
            query += ', ' + definition.Label_Field_Reference__c + ' ';
        }
        if (!String.isBlank(definition.Additional_Detail_Fields__c)) {
            query += ', ' + definition.Additional_Detail_Fields__c + ' ';
        }
        query += 'FROM ' + '';
        

        return query;

    }
    
}